rssnyder/discord-stock-ticker

main.py
Only update price if it has changed.
Remove ticker from logs as loki takes care of job names for us.
I tried messing with timing but I have decided that I dont care about being accurate down to the second. Just sleeping for 1m/1h is fine by me.
=> Enhanced logging 2

main.py
if markets are closed, leave the name alone.
if markets are closed, pick a random message for the activity, and sleep for an hour.
gives my servers a break.
=> use activity for messages if markets closed

README.md, main.py
Add `FREQUENCY` option to update activity more than 60s.
Also, if this is a private instance, allow changing the nickname of the bot along with the activity.
=> add options for frequency

main.py, requirements.txt, utils/coin_gecko.py
Add try/except to all external calls
Remove coingecko SDK for home grown data.
Only display price change in activity if nickname used.
Show crypto 24hr change.
Add weekends to stock afterhours.
Clean up class methods to take inputs rather than env alone.
=> Try nogc overhaul

README.md
Make things a little more clear.
=> clean up and make instructions better

.github/workflows/linter.yml, README.md, main.py
also added documentation tweaks
=> add option for post market price

README.md, main.py, requirements.txt, utils/coin_gecko.py, utils/yahoo.py
gold, silver, oil
replace async calls with direct calls. seems to be more performant.
=> replace sync methods with normal

README.md, main.py
Colors now reflect the day change, and optionally flash the color as the price changes to reflect is going down/up, but then back to the base color.
=> Colors reference day change

main.py
=> removing name changes

main.py
change to after hours pricing for stocks.
=> Stock after hours

main.go, stock.go
fix stock aht and change mixup
=> fix crypto name not using ticker

manager.go
ticker check needs to come after crypto to not fail on crypto additions
=> fix: ticker check order

.github/workflows/deploy.yml, Makefile
=> add openbsd build support

README.md, main.go, manager.go, stock.go, utils/coin_gecko.go
=> feat: add percentage option for changes

manager.go, stock.go, utils/yahoo.go
return json of stock object after adding stock, so users can better confirm their settings.
remove price from the stock json, as it never get updated. will come back at some point.
=> feat: add better return values when adding stocks

stock.go
change crypto prices to cents if they are less than one cent per unit in USD.
=> fix: crypto low prices to cents

main.go, manager.go
allow binding on any interface/port.
allow custom interface/port for redis cache.
=> adding custom interfaces for API and redis

README.md, main.go, manager.go, stock.go
- add 'activity' flag to pass custom messgaes shown in activity section.
- remove arrows, arrows now default if no decorator set
- remove percentage, this was no longer used
- various comments added
- readme redo
=> add custom messages in activity

stock.go
max amount that look good in the sidebar
=> adding decimals to 11

README.md, main.go, manager.go, token.go, token_request.go, utils/oneinch.go
turn matic support into general support for tokens from ETH, BSC, MATIC networks
=> changing matic to token

README.md, ticker.go, ticker_request.go
=> feat: display crypto pair in activity

ticker.go
=> add pair decimal path

ticker.go
=> fix: use open price. not close.

README.md, board.go, board_request.go, gas.go, gas_request.go, holders.go, holders_request.go, manager.go, ticker.go, ticker_request.go, token.go, token_request.go, utils/twelve_data.go
i find myself needing to restart a single bot a lot (to pick up new servers), this will allow us to do it via the API.
=> adding patch request to restart bot

.gitignore, board.go, board_request.go, gas.go, gas_request.go, holders.go, holders_request.go, manager.go, marketcap.go, marketcap_request.go, ticker.go, ticker_request.go, token.go, token_request.go
i want to track which nodes have more calls to CG
=> adding cache hit/miss counter

holders.go
for some reason i had this set to 60 instead of 3600
=> setting holders freq to 1hr

marketcap.go, ticker.go, utils/coin_gecko.go
if the data isnt given to us, we can calculate it, DUH
=> fix: small coin marketcaps

board_request.go, gas.go, gas_request.go, holders_request.go, marketcap_request.go, ticker.go, ticker_request.go, token_request.go, utils/ethgaswatch.go, utils/gas.go, utils/zapper.go
adding more sources for gas prices
adding more decimal points
closes #111
=> fixing nil frequency

manager.go, ticker.go, ticker_request.go
for small tokens, people might want to show the price for 1,000 tokens/coins, to show a larger price.
=> feat: add multiplier for tickers

board.go, board_request.go, gas.go, gas_request.go, holders.go, holders_request.go, marketcap.go, marketcap_request.go, ticker.go, ticker_request.go, token.go, token_request.go
general code quality changes. no functional changes.
edit: ok i added cache usage for ticker bots
=> Code Cleanup #1

marketcap.go, ticker.go, utils/coin_gecko.go
fix error returned when being rate limited.
=> fix: coingecko retries

ticker.go, ticker_request.go
also expose exchange rate in api
=> fix: alt currency for tickers

app.json, board.go, board_request.go, floor.go, floor_request.go, gas.go, gas_request.go, holders.go, holders_request.go, main.go, manager.go, marketcap.go, marketcap_request.go, ticker.go, ticker_request.go, token.go, token_request.go, utils/coin_gecko.go, utils/dex_lab.go, utils/ethgaswatch.go, utils/opensea.go, utils/pancake_swap.go, utils/solanart.go, utils/twelve_data.go, utils/zapper.go
another attempt at cleaning up the project.
=> chore: code cleanup #2

utils/floor.go, utils/solsea.go
This PR add floor price support for Solsea.
=> implement floor price for Solsea

README.md, floor.go, floor_request.go, manager.go
This PR adds the `activity` argument to the floor ticker. It follows #181.
=> Add floor ticker custom activity argument

README.md, token.go
A different version of https://github.com/rssnyder/discord-stock-ticker/pull/187 in which token prices are automatically shown in scientific notation if they are lower than the set decimal value.
=> add scientific format 2

README.md, floor.go, floor_request.go, manager.go, token.go, utils/floor.go
This PR adds the `colors` argument to the floor ticker. Follows up on #182.
=> Add floor ticker colors argument

.gitignore, .goreleaser.yaml, manager.go, ticker.go, utils/yahoo.go
also add more metrics to catch this next time
=> fix: yahoo v10 broke, use v6

holders.go, holders_request.go, manager.go, utils/holders.go
fix: floor decorator in db init
=> fix: holders
